# Generated by Django 3.2.12 on 2022-02-11 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_alter_appointment_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Meeting',
        ),
    ]
